# Generated by Django 4.1 on 2022-08-23 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('Admin_id', models.IntegerField(primary_key=True, serialize=False)),
                ('College', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('Stuid', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Age', models.DateField()),
                ('Gender', models.CharField(max_length=50)),
                ('Degree', models.TextField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.TextField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='picture/%Y/%m/%d')),
                ('Admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Details', to='api.students')),
            ],
        ),
    ]
